// MOB-P1-010: deterministic native sizes from the approved artwork (macOS sips).
import { execFileSync } from 'node:child_process';
import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const mobile = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const root = resolve(mobile, '../..');
const source = resolve(root, 'docs/brand/freeva-app-icon.png');
const tokens = JSON.parse(readFileSync(resolve(root, 'packages/design-tokens/tokens.json')));
function resize(destination, size) {
  mkdirSync(dirname(destination), { recursive: true });
  execFileSync('sips', ['-z', `${size}`, `${size}`, source, '--out', destination]);
}
const catalog = resolve(mobile, 'ios/Runner/Assets.xcassets/AppIcon.appiconset');
const { images } = JSON.parse(readFileSync(resolve(catalog, 'Contents.json')));
for (const image of images) {
  resize(resolve(catalog, image.filename), parseFloat(image.size) * parseFloat(image.scale));
}
const res = resolve(mobile, 'android/app/src/main/res');
for (const [density, scale] of Object.entries({ mdpi: 1, hdpi: 1.5, xhdpi: 2, xxhdpi: 3, xxxhdpi: 4 })) {
  resize(resolve(res, `mipmap-${density}/ic_launcher.png`), 48 * scale);
  const adaptive = resolve(res, `mipmap-${density}/ic_launcher_adaptive.png`);
  // Original artwork fills the 72dp viewport inside the 108dp adaptive canvas.
  // Padding is outside the resting mask; its color comes from design tokens.
  resize(adaptive, 72 * scale);
  execFileSync('sips', ['--padToHeightWidth', `${108 * scale}`, `${108 * scale}`,
    '--padColor', tokens.color.brand.primary.slice(1), adaptive, '--out', adaptive]);
}
const adaptiveDir = resolve(res, 'mipmap-anydpi-v26');
mkdirSync(adaptiveDir, { recursive: true });
writeFileSync(resolve(adaptiveDir, 'ic_launcher.xml'), `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tool/generate_brand_assets.mjs. Approved artwork is flattened. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@mipmap/ic_launcher_adaptive" />
    <foreground android:drawable="@android:color/transparent" />
</adaptive-icon>
`);
mkdirSync(resolve(mobile, 'assets/brand'), { recursive: true });
copyFileSync(resolve(root, 'docs/brand/freeva-brand-symbol.png'),
  resolve(mobile, 'assets/brand/freeva-brand-symbol.png'));
