// Generated by scripts/generate-category-tokens.cjs from packages/design-tokens/tokens.json.
export const CATEGORY_COLORS = [
  "color.brand.primary",
  "color.brand.secondary",
  "color.brand.highlight",
  "color.brand.muted",
  "color.brand.accent",
  "color.neutral.text",
  "color.neutral.textMuted",
  "color.neutral.surface",
  "color.neutral.canvas",
  "color.neutral.onPrimary",
  "color.semantic.success",
  "color.semantic.danger",
  "color.semantic.warning",
  "color.gradient.ctaStart",
  "color.gradient.ctaEnd",
  "color.gradient.splashAccent",
  "color.dark.text",
  "color.dark.textMuted",
  "color.dark.surface",
  "color.dark.canvas",
  "color.dark.onPrimary"
] as const;
